wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.20
    framework: tensorflow
    is_jupyter_run: false
    python_version: 3.7.0
activation:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 100
hidden_layer_size:
  desc: null
  value: 128
optimizer:
  desc: null
  value: adam
seed:
  desc: null
  value: 100
test_size:
  desc: null
  value: 0.3
